### ISSUE TITLE
你好，有个问题想跟你请教一下。

### ISSUE THREAD

**Issue by andansky** [w446108264/ScrollableLayout#2]
现在我用的是viewPage,然后第一个界面是一个ScrollView,第二个跟第三个都是ListView，打开界面的时候默认显示的是ScroView，然后一推到顶了就拉不下来了，我切换到ListView之后再切回来就正常了。这个怎么解决呢？只有第一次打开的时候会有这个情况呢。。。。

**Comment by andansky** [comment]
我又研究了一下，发现不是ScrollView的问题。我现在的问题就是进到页面之后一定要切换一次ViewPage，不然直接推到顶的话就拉不下来了，我不知道为什么会有这个问题，你能给点建议吗，可能出现这种情况的原因是什么呢？应该是我写的代码有问题，但是我又找不出原因，所以希望你能指导一下，谢谢。

**Comment by w446108264** [comment]
暂时没有发现这个问题，你看demo能不能重现你的问题。

如果不能试试分解一个简单的demo，我们来排查一下原因。

**Comment by andansky** [comment]
你好。现在我是三个页面，一个ScrollView，两个ListView。然后时不时就会出现某个页面推到顶之后无法下拉，要切换到别的页面才能拉下来的情况。但是如果我只显示两个页面就不会出现这种情况。这会是什么原因呢？

**Comment by andansky** [comment]
终于解决了，设置viewPager.setOffscreenPageLimit(2)就好了。
